# Generated by Django 5.2 on 2025-05-11 01:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('current_institution', models.CharField(max_length=100)),
                ('study_program', models.CharField(max_length=100)),
                ('academic_year', models.IntegerField()),
                ('average_grade', models.FloatField()),
                ('contact_number', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_records', models.FileField(blank=True, null=True, upload_to='academic_records/')),
                ('financial_documents', models.FileField(blank=True, null=True, upload_to='financial_documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
