# Generated by Django 5.2 on 2025-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extracted_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extracted_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extracted_grades_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extracted_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extracted_previous_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_status',
            field=models.CharField(default='Incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='proof_of_registration',
            field=models.FileField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_records',
            field=models.FileField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='average_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='financial_documents',
            field=models.FileField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
