name: data_layer
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  equatable: ^2.0.5
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0