# Generated by Django 5.2 on 2025-05-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('academic_level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'Doctorate')], max_length=3)),
                ('field_of_study', models.CharField(max_length=100)),
                ('gpa_requirement', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('residency', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_status', models.BooleanField(default=False)),
                ('first_gen_student', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bursaries',
            },
        ),
    ]
